#!/usr/bin/env bash
# =============================================================================
# axupdate — source & script installer
# =============================================================================
# What this script does:
#   1. Installs APT source files for Debian Testing + Security + axpm
#   2. Imports the axpm GPG signing key (if a URL is provided)
#   3. Installs axupdate.py to /usr/local/bin
#   4. Installs the .desktop launcher to /usr/share/applications
#   5. Runs an initial apt update
#
# CONFIGURATION — edit the block below before running.
# Run as root:  sudo bash install.sh
# =============================================================================
set -euo pipefail

# ── USER CONFIGURATION ────────────────────────────────────────────────────────

# Debian mirror to use for the main / updates repositories.
# Leave as-is to use the official CDN, or replace with a local mirror.
# Mirror list: https://www.debian.org/mirror/list
DEBIAN_MIRROR="http://deb.debian.org/debian"

# axpm repository base URL.
# [CHANGE ME] Replace with your real axpm repo URL, e.g.:
#   https://repo.myaxdistro.org/axpm
AXPM_REPO_URI="https://repo.example.com/axpm"

# axpm repository suite/codename.
# [CHANGE ME] Replace with your repo's suite, e.g.: stable, testing, trixie
AXPM_REPO_SUITE="stable"

# axpm GPG key URL (leave empty to skip key import).
# [CHANGE ME] Point to the .asc or .gpg key for your axpm repo, e.g.:
#   https://repo.myaxdistro.org/axpm/axpm-archive-keyring.gpg
AXPM_KEY_URL=""

# Full path to your axupdate.py (the script generated by axupdate).
# Adjust if you placed it elsewhere.
SCRIPT_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/axupdate.py"

# ── END USER CONFIGURATION ────────────────────────────────────────────────────

# Colours for output
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[axupdate]${NC} $*"; }
warn()    { echo -e "${YELLOW}[axupdate] WARNING:${NC} $*"; }
error()   { echo -e "${RED}[axupdate] ERROR:${NC} $*" >&2; exit 1; }

# ── Root check ─────────────────────────────────────────────────────────────

[[ "$EUID" -eq 0 ]] || error "This script must be run as root: sudo bash install.sh"

# ── Dependency check ───────────────────────────────────────────────────────

info "Checking dependencies…"
MISSING=()
for dep in python3 apt apt-get curl gpg notify-send; do
    command -v "$dep" &>/dev/null || MISSING+=("$dep")
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
    warn "Missing optional tools (non-fatal): ${MISSING[*]}"
fi

# PyQt6 check
python3 -c "import PyQt6" 2>/dev/null || {
    warn "PyQt6 not found. Installing python3-pyqt6…"
    apt-get install -y python3-pyqt6 || warn "Could not install python3-pyqt6 automatically. Install it manually."
}

# plyer check (optional, for richer KDE notifications)
python3 -c "import plyer" 2>/dev/null || {
    info "plyer not found — falling back to notify-send for notifications."
    info "To install plyer:  pip install plyer  or  apt install python3-plyer"
}

# ── Step 1 — Install APT source files ──────────────────────────────────────

SOURCES_DIR="/etc/apt/sources.list.d"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

info "Installing APT source files to ${SOURCES_DIR}…"

# Disable any existing /etc/apt/sources.list if it still targets Debian stable
# so it doesn't conflict with our testing entries.
if [[ -f /etc/apt/sources.list ]]; then
    if grep -q "^deb " /etc/apt/sources.list 2>/dev/null; then
        warn "/etc/apt/sources.list contains active entries."
        warn "Consider commenting them out to avoid suite conflicts with Testing."
        warn "Leaving it untouched — review manually if apt warns about mixed suites."
    fi
fi

# Patch mirror URL into the .sources files before copying
sed "s|http://deb.debian.org/debian|${DEBIAN_MIRROR}|g" \
    "${SCRIPT_DIR}/debian-testing.sources" \
    > "${SOURCES_DIR}/debian-testing.sources"
info "  → ${SOURCES_DIR}/debian-testing.sources"

cp "${SCRIPT_DIR}/debian-security.sources" "${SOURCES_DIR}/debian-security.sources"
info "  → ${SOURCES_DIR}/debian-security.sources"

# Patch mirror + repo URL into the .list fallback (kept for reference, disabled by default)
sed "s|http://deb.debian.org/debian|${DEBIAN_MIRROR}|g" \
    "${SCRIPT_DIR}/debian-testing.list" \
    > "${SOURCES_DIR}/debian-testing.list.disabled"
info "  → ${SOURCES_DIR}/debian-testing.list.disabled  (kept as fallback, not active)"

chmod 644 "${SOURCES_DIR}/debian-testing.sources" \
           "${SOURCES_DIR}/debian-security.sources" \
           "${SOURCES_DIR}/debian-testing.list.disabled"

# ── Step 2 — axpm GPG key & source ─────────────────────────────────────────

KEYRING_PATH="/usr/share/keyrings/axpm-archive-keyring.gpg"

if [[ -n "$AXPM_KEY_URL" ]]; then
    info "Importing axpm GPG key from ${AXPM_KEY_URL}…"
    curl -fsSL "$AXPM_KEY_URL" | gpg --dearmor -o "$KEYRING_PATH"
    chmod 644 "$KEYRING_PATH"
    info "  → Saved to ${KEYRING_PATH}"
else
    warn "AXPM_KEY_URL is not set — skipping key import."
    warn "  Set AXPM_KEY_URL in this script and re-run, or import the key manually:"
    warn "  curl -fsSL <YOUR_KEY_URL> | gpg --dearmor | sudo tee ${KEYRING_PATH} >/dev/null"
    # Write axpm.sources only if a real URI was provided
fi

if [[ "$AXPM_REPO_URI" != "https://repo.example.com/axpm" ]]; then
    info "Installing axpm source entry…"
    sed \
        -e "s|https://repo.example.com/axpm|${AXPM_REPO_URI}|g" \
        -e "s|Suites: stable|Suites: ${AXPM_REPO_SUITE}|g" \
        "${SCRIPT_DIR}/axpm.sources" \
        > "${SOURCES_DIR}/axpm.sources"
    chmod 644 "${SOURCES_DIR}/axpm.sources"
    info "  → ${SOURCES_DIR}/axpm.sources"
else
    warn "AXPM_REPO_URI is still the placeholder — skipping axpm.sources installation."
    warn "  Edit AXPM_REPO_URI in this script and re-run to enable the axpm repository."
fi

# ── Step 3 — Install axupdate.py ────────────────────────────────────────────

INSTALL_BIN="/usr/local/bin/axupdate.py"
if [[ -f "$SCRIPT_SRC" ]]; then
    info "Installing axupdate.py → ${INSTALL_BIN}…"
    cp "$SCRIPT_SRC" "$INSTALL_BIN"
    chmod 755 "$INSTALL_BIN"
    chown root:root "$INSTALL_BIN"
else
    warn "axupdate.py not found at ${SCRIPT_SRC}."
    warn "  Copy it manually:  sudo cp axupdate.py ${INSTALL_BIN} && sudo chmod 755 ${INSTALL_BIN}"
fi

# ── Step 4 — Install .desktop launcher ──────────────────────────────────────

DESKTOP_SRC="${SCRIPT_DIR}/../axupdate.desktop"
DESKTOP_DST="/usr/share/applications/axupdate.desktop"
if [[ -f "$DESKTOP_SRC" ]]; then
    info "Installing desktop launcher → ${DESKTOP_DST}…"
    cp "$DESKTOP_SRC" "$DESKTOP_DST"
    chmod 644 "$DESKTOP_DST"
    # Refresh KDE / GTK app caches
    command -v update-desktop-database &>/dev/null && update-desktop-database -q /usr/share/applications || true
    info "  → Desktop launcher installed."
else
    warn "axupdate.desktop not found at ${DESKTOP_SRC} — skipping."
fi

# ── Step 5 — Initial apt update ─────────────────────────────────────────────

info "Running initial apt update (this may take a moment)…"
apt-get update

info ""
info "════════════════════════════════════════════════════════"
info " axupdate installation complete!"
info ""
info " Source files installed:"
info "   ${SOURCES_DIR}/debian-testing.sources"
info "   ${SOURCES_DIR}/debian-security.sources"
[[ "$AXPM_REPO_URI" != "https://repo.example.com/axpm" ]] && \
    info "   ${SOURCES_DIR}/axpm.sources"
info ""
info " Script:   ${INSTALL_BIN}"
info " Launcher: ${DESKTOP_DST}"
info ""
info " Launch:   pkexec python3 ${INSTALL_BIN}"
info "    — or find 'axupdate' in your KDE application menu."
info "════════════════════════════════════════════════════════"
